### PR TITLE
feat(route): support for ignore static file server route prefixes

### PR DESCRIPTION
**Pull request by a631807682**
#### What type of PR is this?

feat

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
`RouterGroup.Static` 查找文件时没有处理路由前缀，增加选项去处理它

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: When we access `/static/1.png`, the file we should find for is `/var/www/1.png` not `/var/www/static/1.png`
```
	h.Static("/static", "/var/www")
```
zh(optional):
当我们访问 `/static/1.png` 时，我们应该找到的文件是 `/var/www/1.png` 而不是 `/var/www/static/1.png`。
```
	h.Static("/static", "/var/www")
```

### CODE REVIEW

**Comment by Duslia** [comment]
This is a break change. Can you provide an option or some other means to avoid it?

**Comment by a631807682** [comment]
> This is a break change. Can you provide an option or some other means to avoid it?

Sure, I will add a config.Options to control it.

**Review by Duslia — APPROVED** [review]

**Comment by welkeyever** [comment]
Already supported this. 
Please check [here](https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go#L152) and [here](https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go#L1220).

But it is a good idea to optimize the example and docs, if you are interested in [it](https://github.com/cloudwego/hertz/issues/699) please let me know.

**Comment by a631807682** [comment]
> Already supported this. Please check [here](https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go?rgh-link-date=2023-03-31T12%3A07%3A00Z#L152) and [here](https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go?rgh-link-date=2023-03-31T12%3A07%3A00Z#L1220).
> 
> But it is a good idea to optimize the example and docs, if you are interested in [it](https://github.com/cloudwego/hertz/issues/699) please let me know.

Yes, I have noticed `PathRewrite` and `NewPathSlashesStripper`, but I think this is a bug, because I think the `relativePath` parameter is not consistent with its behavior. For me, `relativePath` should be a routing-related parameter, but it affects me find files .
For example, when we access `/v1/mysource/test.txt`, we should not find`/source/v1/mysource/test.txt` file, I think we should find  `/source/test.txt` by default `, I'm not sure it's a good idea to let the user write the `PathRewrite`.
```go
h.Static("/v1/mysource", "/source")
```

https://github.com/gin-gonic/gin/blob/153b229fcc6570bac0674d02ab1a629804f29072/routergroup.go#L218

**Comment by welkeyever** [comment]
> 

Do you mean the default behavior is different with Gin/Fiber? Or there exists a scenario that Hertz cannot handle？

**Comment by a631807682** [comment]
> I'm afraid that we cannot break the default behavior at this time. But it is possible to provide detailed documentation guidance.

Ok, i got it.

**Pull request closed without merging**
