### PR TITLE
chore: fix version string

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-core/pull/134158

### CODE REVIEW

**Comment by li-jin-gou** [comment]
hz 和 hertz 是分开打tag，不是version强一致。

**Comment by chenrui333** [comment]
> hz 和 hertz 是分开打tag，不是version强一致。

can you elaborate, I dont think I get it.

**Comment by li-jin-gou** [comment]
> > hz 和 hertz 是分开打tag，不是version强一致。
> 
> can you elaborate, I dont think I get it.

hz's tag is not consistent with hertz's tag and hz did not have any features during this time, so I did not tag to hz.

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz/releases

**Comment by chenrui333** [comment]
> https://github.com/cloudwego/hertz/releases

does that mean, we should track the release tag like this one, `https://github.com/cloudwego/hertz/releases/tag/cmd%2Fhz%2Fv0.6.4`?

**Comment by chenrui333** [comment]
that would actually makes sense.

**Comment by chenrui333** [comment]
Thanks for the explanations, I just filed a PR to update the artifact and livecheck so that it would remove the confusions down the path! 🍻

**Pull request closed without merging**
