### PR TITLE
chore: update mod for govulncheck

### PR DESCRIPTION
**Pull request by haoxins**
#### What type of PR is this?

update the mod for govulncheck

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional):

### CODE REVIEW

**Comment by li-jin-gou** [comment]
> BTW, can we open the `dependabot` for this project?

Add a PR description so we know what it does.

**Comment by haoxins** [comment]
> > BTW, can we open the `dependabot` for this project?
> 
> Add a PR description so we know what it does.

I mean add a file named `dependabot.yml` in the `.github` dir, this content will look like

```
version: 2
updates:
- package-ecosystem: gomod
  directory: ./
  schedule:
    interval: weekly
    day: friday
```

this is the GitHub workflow's function

**Comment by a631807682** [comment]
> BTW, can we open the `dependabot` for this project?

refer to https://github.com/hertz-contrib/registry/pull/36

**Comment by li-jin-gou** [comment]
> > BTW, can we open the `dependabot` for this project?
> 
> refer to [hertz-contrib/registry#36](https://github.com/hertz-contrib/registry/pull/36)

@a631807682 @haoxins  不自动升级依赖的原因是 
1. 升级代码库存在 bk，为了稳定性能不动的依赖升级尽量都不动。
2. 有的库依赖 Go 的高版本特性，用户的 Go 版本分布比较散，而且有些用户还卡了 Go 的版本。

英文可能翻译不准确所以直接用中文了。

**Comment by haoxins** [comment]
okk.
那我先  closed 这个~

**Pull request closed without merging**
