### PR TITLE
style: remove the extra log prefix

### LINKED ISSUE #794: Unnecessary log prefix. Procedure
**Describe the Question**

   The log prefix HERTZ: is not necessary because the prefix string standard is already uniform in the log package: [HERTZ:]，
   this code path is : pkg/network/standard/transport.go:66

image
image

**Reproducible Code**

`t.lock.Unlock()
	if err != nil {
		return err
	}
	hlog.SystemLogger().Infof("HERTZ: HTTP server listening on address=%s", t.ln.Addr().String())
	for {`

**Expected behavior**
Remove the log prefix from the code
  
**Screenshots**

image

**Hertz version:**

Master branch

**Environment:**

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xuanyu\AppData\Local\go-build
set GOENV=C:\Users\xuanyu\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Golang\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Golang\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Golang\GOROOT
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Golang\GOROOT\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\xuanyu\Downloads\hertz-main\hertz-main\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\xuanyu\AppData\Local\Temp\go-build1441738016=/tmp/go-build -gno-record-gcc-switches

### PR DESCRIPTION
**Pull request by hiahia12**
#### What type of PR is this?
style

#### Check the PR title.

- [ ] This PR title match the format: `<type>(optional scope): <description>`.
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io).

#### (Optional) Translate the PR title into Chinese.
移除了多余的日志前缀

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### (Optional) Which issue(s) this PR 
fixes #794

### CODE REVIEW

**Comment by hiahia12** [comment]
微信图片_20230529164033

**Comment by FGYFFFF** [comment]
可以提供一下前后日志对比吗？ hertz 框架内打的日志，都需要有 "HERTZ: " 前缀

**Comment by hiahia12** [comment]
241177840-c0d60147-b86a-41d4-aece-63acf9b99068
之前出现了两个HERTZ:

**Review by li-jin-gou — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]

**Review by welkeyever — APPROVED** [review]
LGTM, thx~

**Comment by Lxy0707s** [comment]
Many hands make light work, thank you for your efforts.

**Pull request merged**
