### PR TITLE
chore: change license header style to avoid format error of buildtag from CI check

### PR DESCRIPTION
**Pull request by li-jin-gou**
#### What type of PR is this?

doc

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).
en: modify header  licenses comment
zh(optional): 修改注释信息为行注释避免 buildtag 格式问题的导致 ci 报错

### CODE REVIEW

**Comment by welkeyever** [comment]
描述在丰富一下哈，这个后续可能被其他pr引用到🤗

**Comment by li-jin-gou** [comment]
refer to https://github.com/golang/go/issues/46169#issuecomment-847420697

**Comment by li-jin-gou** [comment]
> 描述在丰富一下哈，这个后续可能被其他pr引用到🤗

done

**Review by welkeyever — APPROVED** [review]
lgtm

**Review by Duslia — APPROVED** [review]

**Pull request merged**
