### PR TITLE
feat: add round_robin and weight_round_robin algorithm for loadbalance

### LINKED ISSUE #358: Add more load balance algorithms
**Is your feature request related to a problem? Please describe.**

In Hertz, our load balance algorithm only implements weight random. I think it is necessary to support more algorithms.

**Describe the solution you'd like**

Support more algorithms.

### PR DESCRIPTION
**Pull request by L2ncE**
#### What type of PR is this?

feat

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

为负载均衡增加轮询以及加权轮询算法

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

Instance
```go
insList := []discovery.Instance{
    discovery.NewInstance("tcp", "127.0.0.1:8881", 10, nil),
    discovery.NewInstance("tcp", "127.0.0.1:8882", 20, nil),
    discovery.NewInstance("tcp", "127.0.0.1:8883", 50, nil),
    discovery.NewInstance("tcp", "127.0.0.1:8884", 100, nil),
    discovery.NewInstance("tcp", "127.0.0.1:8885", 200, nil),
    discovery.NewInstance("tcp", "127.0.0.1:8886", 500, nil),
}
```
Use weight_random
```go
127.0.0.1:8886
127.0.0.1:8886
127.0.0.1:8882
127.0.0.1:8885
127.0.0.1:8885
127.0.0.1:8885
127.0.0.1:8886
127.0.0.1:8886
127.0.0.1:8886
127.0.0.1:8885
```
Use round_robin
```go
127.0.0.1:8881
127.0.0.1:8882
127.0.0.1:8883
127.0.0.1:8884
127.0.0.1:8885
127.0.0.1:8886
127.0.0.1:8881
127.0.0.1:8882
127.0.0.1:8883
127.0.0.1:8884
```
Use weight_round_robin
```go
127.0.0.1:8886
127.0.0.1:8885
127.0.0.1:8886
127.0.0.1:8884
127.0.0.1:8886
127.0.0.1:8886
127.0.0.1:8885
127.0.0.1:8886
127.0.0.1:8883
127.0.0.1:8886
```

#### Which issue(s) this PR fixes:

Fixes #358

### CODE REVIEW

**Comment by Duslia** [comment]
I think Hertz-contrib is more suitable to put this code.

**Comment by L2ncE** [comment]
> I think Hertz-contrib is more suitable to put this code. What's your opinion?

My opinion is that the load balancer which adapts to the third-party service registry can be placed in hertz-contrib, and this kind of load balancing algorithm is placed directly in the main library.

**Comment by Duslia** [comment]
I don't think it should be placed in the main repository or Hertz-Contrib by whether there are third-party dependencies. I should be decided by the design. And the random implementation placed in the main repo is because it's just a simple implementation. Hertz is a HTTP framework, not a framework provided loadbalance algorithm, so I think it's better to be placed in Hertz-COntrib.

**Comment by L2ncE** [comment]
> 

Agreed, I'll put it in hertz-contrib. 
Thx.

**Comment by Duslia** [comment]
Please create pr in repo: https://github.com/hertz-contrib/loadbalance

**Comment by L2ncE** [comment]
> Please create pr in repo: https://github.com/hertz-contrib/loadbalance

got it, thx.

**Pull request closed without merging**
