### PR TITLE
fix(hz): use defer in the for loop 

### PR DESCRIPTION
**Pull request by SeigeC**
#### What type of PR is this?
fix

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: fix: use defer in the for loop 
zh(optional): fix: 在 for 循环中直接使用 defer

### CODE REVIEW

**Comment by L2ncE** [comment]
Hi! Thanks for your PR, please add PR type according to the PR template and en description.

**Comment by welkeyever** [comment]
Maybe provide more information about this `fix`? Is there any bug related to this fix?

**Comment by SeigeC** [comment]
> hz
i didn't find any similar errors

**Comment by Duslia** [comment]
> i didn't find any similar errors

Sorry, I can't understand you. Can you describe more detaily?

**Comment by FGYFFFF** [comment]
good issue, I will check it

**Review by FGYFFFF — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
