### PR TITLE
test: add more tests for pkg/app/context

### PR DESCRIPTION
**Pull request by mamil**
#### What type of PR is this?
test: Adding missing tests or correcting existing tests
pkg/app/context test coverage increased from 68.6% to 73.8%

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
为pkg/app/context添加更多测试

#### (Optional) More detail description for this PR(en: English/zh: Chinese).
en: Add tests for TraceInfo Get and Set operations for pkg/app/context
zh(optional): 为pkg/app/context添加TraceInfo读写操作的测试

#### Which issue(s) this PR fixes:
#257

### CODE REVIEW

**Comment by welkeyever** [comment]
Thanks for your committing! Please follow the template's rule in the PR description - maybe check the other PR in history.

**Comment by mamil** [comment]
@welkeyever description updated

**Comment by li-jin-gou** [comment]
@mamil  Hello [mamil](https://github.com/mamil) Would you like to increase the coverage to around 80%?

**Comment by mamil** [comment]
@li-jin-gou I will add more test cases in the future, but I think submitting too much code at one time will put pressure on the reviewer, what do you think?

**Comment by li-jin-gou** [comment]
> @li-jin-gou I will add more test cases in the future, but I think submitting too much code at one time will put pressure on the reviewer, what do you think?

Ok

**Comment by mamil** [comment]
@li-jin-gou coverage reached 73.8%, I think we should commit the code first.

**Review by welkeyever — APPROVED** [review]
LGTM, thx~

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
