### PR TITLE
optimize: func checkPathValid returns true if the path is valid

### PR DESCRIPTION
**Pull request by wangbei98**
#### What type of PR is this?

optimize

#### What this PR does / why we need it (English/Chinese):

en: change the default return
zh: 更改默认返回值

### CODE REVIEW

**Review by li-jin-gou — APPROVED** [review]

**Comment by FGYFFFF** [comment]
修改的原因是啥？

**Comment by wangbei98** [comment]
> 修改的原因是啥？

默认返回值和函数名不一致
returns “valid” (“true” for checkPathValid) by default

**Review by welkeyever — APPROVED** [review]

**Comment by welkeyever** [comment]
> > 修改的原因是啥？
> 
> 默认返回值和函数名不一致 returns “valid” (“true” for checkPathValid) by default

感谢贡献~正式merge前，辛苦签署一下cla哈

**Comment by wangbei98** [comment]
>

**Pull request merged**
