### PR TITLE
test: add test for protocol http1

### PR DESCRIPTION
**Pull request by a631807682**
#### What type of PR is this?

test

#### Check the PR title.

- [x] This PR title match the format: `<type>(optional scope): <description>`.
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io).

#### (Optional) Translate the PR title into Chinese.
添加 pkg/protocol/http1 单测

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: Supplement unit test for pkg/protocol/http1, coverage increased from 53.30% to 81.9%.
zh(optional): 补充 pkg/protocol/http1 的单元测试，覆盖率从 53.30% 提高到了 81.9%。

其他疑问:
zr 已经 release，并且没有别的引用 https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/http1/server.go#L328-L332 
这里再判断一遍是必要的吗？https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/http1/server.go#L353-L356

#### (Optional) Which issue(s) this PR fixes:

related to https://github.com/cloudwego/hertz/issues/257

### CODE REVIEW

**Comment by li-jin-gou** [comment]
thanks💖

**Comment by Duslia** [comment]
It seems that it's useless

**Review by welkeyever — DISMISSED** [review]
Thanks a lot! LGTM

**Comment by welkeyever** [comment]
As for the "duplicated code" you may trigger another pr for it~

**Comment by a631807682** [comment]
> As for the "duplicated code" you may trigger another pr for it~

I will create another PR for it

**Comment by li-jin-gou** [comment]
@a631807682  There's a conflict that needs to be resolved.

**Comment by a631807682** [comment]
> @a631807682 There's a conflict that needs to be resolved.

done

**Review by li-jin-gou — APPROVED** [review]

**Review by welkeyever — APPROVED** [review]

**Pull request merged**
