### PR TITLE
fix: uri normalize in windows

### PR DESCRIPTION
**Pull request by Duslia**
#### What type of PR is this?

fix
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
修复 uri 在 windows 下的统一化

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: fix uri normalize in windows which is the #536 left problem. Before fixed, `a` won't be normalized to `/a` in windows scenario
zh(optional): 修复 uri 在 windows 下的统一化，#536 遗留问题。未修复之前，`a` 不会被归一化为 `/a`

### CODE REVIEW

**Comment by welkeyever** [comment]
This is why fasthttp do it in a redundant way😂
cc #229 @ruokeqx

**Comment by ruokeqx** [comment]
> This is why fasthttp do it in a redundant way😂 cc #229 @ruokeqx

I know it, as said before in https://github.com/cloudwego/hertz/pull/229#issuecomment-1236385614, both “C:\a\b\c\fs.go” and "C:/a/b/c/fs.go" work. Maybe this fix is more normative.

**Comment by ruokeqx** [comment]
What about deleting the function `TestParsePathWindows` and `testParsePathWindows` in `uri_test.go`. @Duslia

**Comment by Duslia** [comment]
> What about deleting the function `TestParsePathWindows` and `testParsePathWindows` in `uri_test.go`. @Duslia

I have tested and it can work. Thanks a lot.

**Review by welkeyever — APPROVED** [review]

**Review by FGYFFFF — APPROVED** [review]

**Pull request merged**
