### PR TITLE
Standardize the use of HTTP status codes in HZ tools and unit tests

### PR DESCRIPTION
**Pull request by chenghonour**
#### What type of PR is this?

optimize

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
规范在HZ工具与单元测试HTTP status codes的使用

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: Standardize the use of HTTP status codes in HZ tools and unit tests, and uniformly use the constants in the consts package to help better semantic understanding and reduce the possibility of input errors.
zh(optional): 规范在HZ工具与单元测试中HTTP status codes的使用，统一使用consts包里的常量，以助于更好的语义化理解且减少输入出错的可能。

### CODE REVIEW

**Review by li-jin-gou — DISMISSED** [review]

**Comment by FGYFFFF** [comment]
Can you "grep" globally to see if there are any other similar cases?

**Comment by chenghonour** [comment]
> Can you "grep" globally to see if there are any other similar cases?

yes, I try it already.

**Comment by FGYFFFF** [comment]
> > Can you "grep" globally to see if there are any other similar cases?
> 
> yes, I try it already.

OK, then there is no problem. Let's fix the CI first.

**Review by FGYFFFF — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]

**Comment by li-jin-gou** [comment]
LGTM

**Pull request merged**
