### PR TITLE
fix: update ut for assert.NotNil

### LINKED ISSUE #1178: fix assert.NotNil not working
**Describe the bug**

使用 assert 的 NotNil 断言时不生效

**Replay**
测试代码：
```golang
import  "github.com/cloudwego/hertz/pkg/common/test/assert"
func TestAssertNotNil(t *testing.T) {
	var test interface{}
	assert.NotNil(t, test)
	fmt.Println("test 值不为空")
}
```
image

**Hertz version:**

`
version: 0.9.2
`

### PR DESCRIPTION
**Pull request by ElvisWai**
#### What type of PR is this?
fix

#### Check the PR title.

- [X] This PR title match the format: \<type\>(optional scope): \<description\>
- [X] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
修复 assert的 NotNil 不生效。（参数判断有误）

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional):
见 https://github.com/cloudwego/hertz/issues/1179

#### (Optional) Which issue(s) this PR fixes:

close #1178

### CODE REVIEW

**Comment by ElvisWai** [comment]
@welkeyever 改好了，approval 一下试试 workflows 结果

**Comment by welkeyever** [comment]
> @welkeyever 改好了，approval 一下试试 workflows 结果

pr 按照模板来哈，这个模板是关联自动发版的，格式需要 follow 下

**Comment by ElvisWai** [comment]
> ci 里可以直接看到结果，应该还有点问题： image

那个问题我本地用 go 1.20.14 的容器跑 ut 是成功。挺疑惑在 workflows 里面为啥会不通过 😭

**Review by welkeyever — APPROVED** [review]
LGTM, thx~

**Review by Duslia — APPROVED** [review]

**Pull request merged**
