### PR TITLE
fix: prevent goroutine leak

### PR DESCRIPTION
**Pull request by mamil**
#### What type of PR is this?

fix

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
防止goroutine泄露

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: Prevent goroutine leaks. If ctx.Done() happens first, executeOnShutdownHooks will be leaked here. Although it will exit soon, it is more elegant not to leak resources.
zh(optional): 防止goroutine泄露。如果ctx.Done()先发生，executeOnShutdownHooks这里将会泄露，虽然马上就要退出了，但不泄露资源更加优雅一点。

### CODE REVIEW

**Comment by Duslia** [comment]
Why assigning a capacity for chan can prevent this from happening

**Comment by welkeyever** [comment]
Thanks for your reporting. 
However, as the scene you mention here is at the closing phase, this blocked goroutine will be cleaned very soon after the exits of main process. 
So there will not be a "leak" - considering the impact of scheduling, the line you've changed here may not actually have the change to execute.

**Comment by mamil** [comment]
@welkeyever  Indeed, this issue does not have much impact, so should we close this pr or merge it?

**Comment by Duslia** [comment]
I think there is no need to merge it.

**Comment by welkeyever** [comment]
> @welkeyever Indeed, this issue does not have much impact, so should we close this pr or merge it?

At present, I will close this pr first. If there are any substantial optimizations or fixes, we will be very welcome~

**Pull request closed without merging**
